#!/bin/bash
# shellcheck disable=SC2068,SC2086,SC2102
# A simple shell script to improve testing Cobbler in e.g. a VM
# Tested with openSUSE Tumbleweed
# Author: Dominik Gedon (dgedon@suse.de)
# -------------------------------------------------------------

## adjust to your needs
HOST_ISOS="$HOME/isos"
MOUNTPOINT="/mnt2"
GIT_DIR="$HOME/cobbler"

## general information
VERSION=0.6
NAME=cob

version () {
    echo $NAME $VERSION
}

mount_vm_dirs () {
    if [ ! -e $HOST_ISOS ]; then
        mkdir $HOST_ISOS
    fi

    echo "Mounting host ISO directory to $HOST_ISOS"
    sudo mount -t 9p -o trans=virtio,version=9p2000.L /mnt $HOST_ISOS
}

mount_dirs () {
    if [ ! -e $MOUNTPOINT ]; then
        mkdir $MOUNTPOINT
    fi

    echo "$MOUNTPOINT already mounted. Unmounting"
    if mount | grep $MOUNTPOINT; then
        sudo umount $MOUNTPOINT
    fi

    echo "Mounting ISO $2 to $MOUNTPOINT"
    sudo mount -t iso9660 -o loop,ro $2 $MOUNTPOINT
}

clone_cobbler () {
    if [ ! -e $GIT_DIR ]; then
        if ! which git > /dev/null; then
            echo "git not found. Installing it."
            sudo zypper install -y git
        fi
        git clone https://github.com/cobbler/cobbler.git $GIT_DIR
    fi
}

install_deps () {
    echo "Installing dependencies"
    sudo zypper install -y python3 python3-cheetah python3-netaddr python3-simplejson python3-librepo python3-devel python3-pip python3-setuptools python3-wheel python3-distro python3-coverage python3-ldap python3-Sphinx apache2 apache2-devel apache2-mod_wsgi-python3 python3-dnspython rsync fence-agents genders xorriso tftp  supervisor ipmitool acl python3-PyYAML python3-schema docker
    pip3 install file-magic ldap3 pymongo tornado dnspython mod_wsgi prospector[with_pyroma] prospector[with_frosted] prospector[with_mypy] prospector[with_vulture]

    echo "Building and installing codacy cli"
    curl -L https://github.com/codacy/codacy-analysis-cli/archive/master.tar.gz | tar xvz
    cd codacy-analysis-cli-* && sudo make install
}

codacy_check () {
    # TODO: write usage submenu for this and add possibility to specify codacy tool
    # $2 dir
    # $3 toolname: prospector, codacy
    # $4 extra params for tool
    # $5 codacy token
    if ! which codacy-analysis-cli > /dev/null; then
        echo "codacy-analysis-cli not installed. Plese use $NAME install_deps first"
    fi
    if [ -z "$2" ]; then
        echo "You have to specify a directory"
    else
        echo "Running codacy cli with pylint"
        codacy-analysis-cli analyze --directory "$2" --tool pylintpython3
        echo "Running codacy cli with bandit"
        codacy-analysis-cli analyze --directory "$2" --tool bandit
    fi
}

prospector_check () {
    if ! which prospector > /dev/null; then
        echo "Prospector not installed. Plese use $NAME install_deps first"
    fi
    if [ -z "$2" ]; then
        echo "You have to specify a directory"
    else
        echo "$2"
        echo "Running prospector with pyroma"
        prospector --tool pyroma "$2"
    fi
}

build_cobbler () {
    git status
    echo "Get latest updates from GitHub"
    # the branch has to be selected manually
    cd $GIT_DIR && git pull
    echo "Building Cobbler"
    sudo make install -C $GIT_DIR
    restart_cobbler
    echo "Cobbler version"
    cobbler version
}

clean_cobbler () {
    echo "Clean up Cobbler"
    sudo rm /var/lib/cobbler/collections/distros/*
    sudo rm /var/lib/cobbler/collections/profiles/*
    sudo rm /var/lib/cobbler/collections/systems/*
    sudo rm /var/lib/cobbler/collections/menus/*
    sudo rm /var/lib/cobbler/collections/profiles/*
    sudo rm /var/lib/cobbler/collections/repos/*
    sudo rm /var/lib/cobbler/collections/images/*
    sudo rm /var/lib/cobbler/collections/files/*
    sudo rm -rf /srv/tftpboot
    sudo rm -rf /srv/www/cobbler
    cobbler sync
    sudo rm /var/log/cobbler/cobbler.log
    restart_cobbler
}

import_distro () {
    echo "Importing distro $2"
    cobbler import --name=$2 --path=$MOUNTPOINT
}

create_distro () {
    touch $GIT_DIR/kernel
    touch $GIT_DIR/initrd
    KERNEL="$GIT_DIR/kernel"
    INITRD="$GIT_DIR/initrd"

    echo "Add distro with name $2"
    cobbler distro add --name=$2 --kernel=$KERNEL --initrd=$INITRD
}

create_profile () {
    echo "Add profile with name $2 and distro $3"
    cobbler profile add --name=$2 --distro=$3
}

create_system () {
    echo "Add system with name $2"
    cobbler system add --name=$2 --profile=$3
}

restart_cobbler () {
    if systemctl status cobblerd | grep inactive; then
        echo "Starting cobblerd"
        sudo systemctl start cobblerd
    else
        echo "Restarting cobblerd service"
        sudo systemctl restart cobblerd
    fi
    echo "Sleep 3s"
    sleep 3s
    sudo systemctl status cobblerd
}

watch_log () {
    tail -f /var/log/cobbler/cobbler.log
}

open_log () {
    less /var/log/cobbler/cobbler.log
}

check_par () {
    if [ -z "$2" ]; then
        echo "You have to supply 1 parameter."
        exit 1;
    fi
}

check_par2 () {
    if [ -z "$2" ] && [ -z "$3" ]; then
        echo "You have to supply 2 parameters."
        exit 1;
    fi
}

show_help () {
    echo "Usage: $NAME OPTION [PARAMETER]"
    echo "Helper utility/wrapper for testing Cobbler"
    echo
    echo "  help        Print this help message"
    echo "  build       Build and install Cobbler in $GIT_DIR"
    echo "  clean       Clean Cobbler files"
    echo "  clone       Clone the cobbler repo to $GIT_DIR"
    echo "  codacy      Check the code with Codacy CLI"
    echo "  deps        Install dependencies"
    echo "  import      Import a mounted distro into Cobbler"
    echo "  mount       Mount ISO to $MOUNTPOINT"
    echo "  vmount      Mount host directory to $HOST_ISOS in guest"
    echo "  distro      Create a new distro"
    echo "  profile     Create a new profile from distro"
    echo "  prospector  Check the code with prospector"
    echo "  system      Create a new system from profile"
    echo "  log         Open the log file"
    echo "  wlog        Watch the log file"
    echo "  version     Show the version number"
    echo ""
    echo "Examples:"
    echo ""
    echo "  $NAME mount openSUSE-Leap-15.3-DVD-x86_64-Current.iso"
    echo "  $NAME import name"
    echo "  $NAME distro name"
    echo "  $NAME profile name distro_name"
    echo "  $NAME system name profile_name"
    echo "  $NAME codacy ~/git/cobbler/cobbler"
    echo "  $NAME prospector ~/git/cobbler"
    exit 1
}

# main routine
case $1 in
    codacy)
        codacy_check $@
        ;;
    prospector)
        prospector_check $@
        ;;
    mount)
        check_par $@
        mount_dirs $@
        ;;
    vmount)
        mount_vm_dirs
        ;;
    clean)
        clean_cobbler
        ;;
    clone)
        clone_cobbler
        ;;
    deps)
        install_deps
        ;;
    build)
        build_cobbler
        ;;
    restart)
        restart_cobbler
        ;;
    import)
        check_par $@
        import_distro $@
        ;;
    distro)
        check_par $@
        create_distro $@
        ;;
    profile)
        check_par2 $@
        create_profile $@ $@
        ;;
    system)
        check_par2 $@
        create_system $@ $@
        ;;
    log)
        open_log
        ;;
    wlog)
        watch_log
        ;;
    version)
        version
        ;;
    help | --help)
        show_help
        ;;
    *)
        show_help
        ;;
esac
